previousnext/containers

php/5.6-dev/README.md
php/7.0-dev/README.md
php/7.1-dev/README.md
php/7.x-dev/README.md

fix typo of documentation

---

php/5.6-dev/Dockerfile
php/7.0-dev/Dockerfile
php/7.1-dev/Dockerfile
php/7.x-dev/Dockerfile

* Add to dev containers for additional info, eg. Vagrnat or Docker?
* Don't add to production containers, they should not have that info

Add ENV_TYPE variables for identification

---

Makefile
solr/4.x/Dockerfile
solr/4.x/entrypoint.sh
solr/5.x/Dockerfile
solr/5.x/conf/elevate.xml
solr/5.x/conf/mapping-ISOLatin1Accent.txt
solr/5.x/conf/protwords.txt
solr/5.x/conf/schema.xml
solr/5.x/conf/schema_extra_fields.xml
solr/5.x/conf/schema_extra_types.xml
solr/5.x/conf/solrconfig.xml
solr/5.x/conf/solrconfig_extra.xml
solr/5.x/conf/solrcore.properties
solr/5.x/conf/stopwords.txt
solr/5.x/conf/synonyms.txt
solr/5.x/scripts/heap.sh

* Initial work for solr:5.x
* Extended from solr:5.5.4
* Sets up a core by default

Adds previousnext/solr:5.x

---

php/5.6/base/Dockerfile
php/7.0/base/Dockerfile
php/7.1/base/Dockerfile
php/7.x/base/Dockerfile

Adds the Github to known_hosts
```bash
ssh git@github.com on local
```
Nope
N/A
N/A
Nope
Nope

Adds github known_hosts to php images

---

php/5.6/base/Dockerfile
php/5.6/base/status.conf
php/7.0/base/Dockerfile
php/7.0/base/status.conf
php/7.1/base/Dockerfile
php/7.1/base/status.conf
php/7.x/base/Dockerfile
php/7.x/base/status.conf

Enables mod_status
We will be able to use this as a stepping stone for better monitoring.
* Rebuild containers
* Use them on a local project
* View `http://localhost/server-status`
https://github.com/neezgee/apache_exporter
N/A
N/A
N/A

Adds mod_status reporting for metrics gathering

---

php/5.6/base/Dockerfile
php/7.0/base/Dockerfile
php/7.1/base/Dockerfile
php/7.x/base/Dockerfile

Adds m8s binary

---

php/5.6/dev/Dockerfile
php/7.0/dev/Dockerfile
php/7.1/dev/Dockerfile
php/7.x/dev/Dockerfile

pnx-d8 is using circleci for patchy builds now. In order to create a PR we need hub installed.
Lets add it to the dev containers.

Add hub command

---

.circleci/config.yml
cf-log-analyzer/Dockerfile
cf-log-analyzer/Makefile
cf-log-analyzer/README.md
cf-log-analyzer/cloud_front.rb

Adds a new container image for analysing cloudfront access logs.
Load up the amaysim aws credentials and fetch cf logs.
```bash
aws s3 cp "s3://cf-d22eumuknpgyy2-logs/" ./cf-logs \
--recursive \
--exclude "*" \
--include "EVFEUICLDHBSZ.2017-12-13*"
```
Run log analysis.
```bash
docker run --rm -v $(pwd)/cf-logs:/data previousnext/cf-log-analyzer
```
Open report.
```bash
open ./cf-logs/report.html
```
I worked on this when looking into issues earlier in the week.
* https://redmine.previousnext.com.au/issues/48552

CloudFront Log Analyzer

---

php/5.6-apache-jessie/dev/Dockerfile
php/7.x-apache-jessie/dev/Dockerfile
php/7.x-apache-stretch/dev/Dockerfile

Fix order of PATH so /usr/bin trumps /node_modules/.bin

---

.circleci/config.yml
gastonjs/Dockerfile

Adds a scheduled build each week for all our images.
Also alphabetises the jobs for easier scanning.

Adds missing jobs & schedule build.

---

php/apache/Dockerfile
php/apache/dev/Dockerfile

Adds `jq` binary for dealing with json on the command line.

Added jq tool to dev images.

---

php/apache/dev/Dockerfile

Temporarily commented out g++

---

php/apache/Makefile

This should fix all the dramas!

Use alpine-3.8 for php-apache:7.2 image

---

php/apache/Dockerfile
php/apache/drush.yml
php/apache/tests/drush9.yml

https://redmine.previousnext.com.au/issues/52600
Signed-off-by: Jibran Ijaz <jibran.ijaz@gmail.com>

[#52600] Added drush.yml for drush9.

---

athenapdf/Dockerfile
gastonjs/Dockerfile
php/5.6-apache-jessie/base/Dockerfile
php/7.x-apache-jessie/base/Dockerfile
php/apache/Dockerfile

Fix jessie repos

---

php/apache/Dockerfile
php/apache/skpr.php

Add skpr.php to php containers

---

passenger/base/Dockerfile

Pin bundler at <2.0 for rails compat

---

php/7.x-apache-jessie/base/Dockerfile

Add fileinfo extension to legacy php containers

---

golang/Dockerfile
golang/Makefile

Adds updated golang versions

---

Dockerfile
athenapdf/Dockerfile
chrome-headless/Dockerfile
clamd/Dockerfile
gastonjs/Dockerfile
oauth2_proxy/Dockerfile
passenger/base/Dockerfile
passenger/dev/Dockerfile
php/5.6-apache-jessie/base/Dockerfile
php/5.6-apache-jessie/dev/Dockerfile
php/7.x-apache-jessie/base/Dockerfile
php/7.x-apache-jessie/dev/Dockerfile
php/apache/Dockerfile
php/apache/dev/Dockerfile
pnx-packager/Dockerfile
solr/4.x/Dockerfile

Adds missing docconv deps

---

php/apache/Dockerfile

Bump new relic agent for 7.3 compat

---

athenapdf/Dockerfile

Fix athena build due to missing keys

---

athenapdf/Dockerfile
php/apache/Dockerfile
php/apache/Makefile
php/apache/dev/tests/alpine3.10.yml

Upgrade to alpine 3.10 for php-apache

---

php/apache/dev/Dockerfile

https://github.com/previousnext/m8s/releases/tag/v0.9.0

Bumped m8s to v0.9.0.

---

node/Dockerfile
node/Makefile

Adds node 12

---

solr/4.x/conf/solr/elevate.xml
solr/4.x/conf/solr/schema.xml
solr/4.x/conf/solr/solrconfig.xml
solr/4.x/conf/solr/solrcore.properties

Some details of this may be confidential, so created an issue summary here: https://previousnext.slack.com/archives/CBRQ921JM/p1582684770000200

Solr 4.x config update for search_api_solr:8.x-1.x

---

solr/4.x/conf/solr/schema.xml
solr/4.x/conf/solr/solrcore.properties

Update solr 4.x to match SAPI 8.x-1.x HEAD.

---

puppeteer/package-lock.json
puppeteer/package.json

Security updates

---

node/Makefile

Add node 14

---

php-apache/Dockerfile

Add composer2

---

passenger/base/Dockerfile

Adds skprmail to passenger image

---

node/Makefile

Adds Node 16
As per https://github.com/previousnext/containers/pull/170

Add node 16
